services:
  - type: web
    name: aafnotech-admin
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: "3000"
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SECRET
        sync: false
